const PERMISSION_USER_KEY = {
  // User
  LIST_ALL_USER: "USER.LIST_ALL",
  LIST_USER: "USER.LIST",
  GET_ME: "USER.GET_ME",
  GET_DETAIL_USER: "USER.GET_DETAIL",
  UPDATE_USER: "USER.UPDATE",
  DELETE_USER: "USER.DELETE",
  CREATE_USER: "USER.CREATE",
  CHANGE_PASSWORD_USER: "USER.CHANGE_PASSWORD_USER",
  EXPORT_EXCEL_LIST_ALL_USER: "USER.EXPORT_EXCEL_LIST_ALL",
  // User dependents
  ADD_USER_DEPENDENTS: "USER_DEPENDENTS.ADD_USER_DEPENDENTS",
  UPDATE_USER_DEPENDENTS: "USER_DEPENDENTS.UPDATE_USER_DEPENDENTS",
  DELETE_USER_DEPENDENTS: "USER_DEPENDENTS.DELETE_USER_DEPENDENTS",
  GET_USER_DEPENDENTS: "USER_DEPENDENTS.GET_USER_DEPENDENTS",
  LIST_ALL_USER_DEPENDENTS: "USER_DEPENDENTS.LIST_ALL_USER_DEPENDENTS",
  LIST_USER_DEPENDENTS: "USER_DEPENDENTS.LIST_USER_DEPENDENTS",
};

const PERMISSION_ROLE_KEY = {
  // Role
  LIST_ROLE: "ROLE.LIST",
  GET_ME_ROLE: "ROLE.GET_ME",
  GET_DETAIL_ROLE: "ROLE.GET_DETAIL",
  CREATE_ROLE: "ROLE.CREATE",
  UPDATE_ROLE: "ROLE.UPDATE",
  DELETE_ROLE: "ROLE.DELETE",
  ADD_ROLE_FOR_USER: "ROLE.ADD_ROLE_FOR_USER",
  VIEW_AUTHORIZED_USERS: "ROLE.VIEW_AUTHORIZED_USERS",
  ADD_UPDATE_REMOVE_ROLE_FOR_USER: "ROLE.ADD_UPDATE_REMOVE_ROLE_FOR_USER",
};

const PERMISSION_SALARY_MANAGER_KEY = {
  // Salary
  LIST_ALL_SALARY: "SALARY_MANAGER.LIST_ALL",
  LIST_SALARY: "SALARY_MANAGER.LIST",
  GET_ME_SALARY: "SALARY_MANAGER.GET_ME",
  GET_DETAIL_SALARY: "SALARY_MANAGER.GET_DETAIL",
  CREATE_SALARY: "SALARY_MANAGER.CREATE",
  CREATE_ALL_SALARY: "SALARY_MANAGER.CREATE_ALL",
  UPDATE_SALARY: "SALARY_MANAGER.UPDATE",
  DELETE_SALARY: "SALARY_MANAGER.DELETE",
  ADD_SALARY_PROJECT: "SALARY_MANAGER.ADD_SALARY_PROJECT",
  DELETE_SALARY_PROJECT: "SALARY_MANAGER.DELETE_SALARY_PROJECT",
  ADD_SALARY_OTHER: "SALARY_MANAGER.ADD_SALARY_OTHER",
  DELETE_SALARY_OTHER: "SALARY_MANAGER.DELETE_SALARY_OTHER",
  ADD_ONSITE_SALARY: "SALARY_MANAGER.ADD_ONSITE_SALARY",
  DELETE_ONSITE_SALARY: "SALARY_MANAGER.ADD_ONSITE_SALARY",
  ADD_OT_SALARY: "SALARY_MANAGER.ADD_OT_SALARY",
  DELETE_OT_SALARY: "SALARY_MANAGER.DELETE_OT_SALARY",
  ADD_SALARY_DEDUCTION: "SALARY_MANAGER.ADD_SALARY_DEDUCTION",
  DELETE_SALARY_DEDUCTION: "SALARY_MANAGER.DELETE_SALARY_DEDUCTION",
  ACCEPT_SALARY_ONSITE: "SALARY_MANAGER.ACCEPT_SALARY_ONSITE",
  ACCEPT_SALARY_OT: "SALARY_MANAGER.ACCEPT_SALARY_OT",
  ACCEPT_SALARY_TOTAL: "SALARY_MANAGER.ACCEPT_SALARY_TOTAL",
  LOCK_SALARY: "SALARY_MANAGER.LOCK_SALARY",
  UNLOCK_SALARY: "SALARY_MANAGER.UNLOCK_SALARY",
};

const PERMISSION_SALARY_APPROVAL_KEY = {
  SALARY_APPROVAL: "SALARY_APPROVAL.SALARY_APPROVAL",
  LIST_SALARY_APPROVAL: "SALARY_APPROVAL.LIST",
  LIST_ALL_SALARY_APPROVAL: "SALARY_APPROVAL.LIST_ALL",
  GET_DETAIL_SALARY_APPROVAL: "SALARY_APPROVAL.GET_DETAIL",
};

const PERMISSION_ON_LEAVE_KEY = {
  // On leave
  LIST_ALL_ON_LEAVE: "ON_LEAVE.LIST_ALL_ON_LEAVE",
  LIST_ON_LEAVE: "ON_LEAVE.LIST_ON_LEAVE",
  GET_DETAIL_ON_LEAVE: "ON_LEAVE.GET_DETAIL",
  ADD_ON_LEAVE: "ON_LEAVE.ADD_ON_LEAVE",
  UPDATE_ON_LEAVE: "ON_LEAVE.UPDATE_ON_LEAVE",
  DELETE_ON_LEAVE: "ON_LEAVE.DELETE_ON_LEAVE",
  ACCEPT_ON_LEAVE: "ACCEPT_ON_LEAVE",
};

const PERMISSION_EVENT_KEY = {
  // Event
  LIST_ALL_EVENT: "EVENT.LIST_ALL_EVENT",
  LIST_EVENT: "EVENT.LIST_EVENT",
  GET_DETAIL_EVENT: "EVENT.GET_DETAIL_EVENT",
  ADD_EVENT: "EVENT.ADD_EVENT",
  DELETE_EVENT: "EVENT.DELETE_EVENT",
  UPDATE_EVENT: "EVENT.UPDATE_EVENT",
};

const PERMISSION_WORK_CALENDAR_KEY = {
  // Event
  LIST_ALL: "WORK_CALENDAR.LIST_ALL",
  LIST: "WORK_CALENDAR.LIST",
  GET_DETAIL: "WORK_CALENDAR.GET_DETAIL",
  LOCK_WORK_CALENDAR: "WORK_CALENDAR.LOCK_WORK_CALENDAR",
  UNLOCK_WORK_CALENDAR: "WORK_CALENDAR.UNLOCK_WORK_CALENDAR",
};

const PERMISSION_PROJECT_KEY = {
  // Project
  LIST_ALL: "PROJECT.LIST_ALL",
  LIST: "PROJECT.LIST",
  GET_DETAIL: "PROJECT.GET_DETAIL",
  ADD: "PROJECT.ADD",
  UPDATE: "PROJECT.UPDATE",
  DELETE: "PROJECT.DELETE",
  ADD_MEMBER: "PROJECT.ADD_MEMBER",
  EDIT_MEMBER: "PROJECT.EDIT_MEMBER",
  DELETE_MEMBER: "PROJECT.DELETE_MEMBER",
};

const PERMISSION_POSITION_KEY = {
  // Position
  LIST_ALL: "POSITION.LIST_ALL",
  LIST: "POSITION.LIST",
  GET_DETAIL: "POSITION.GET_DETAIL",
  ADD: "POSITION.ADD",
  UPDATE: "POSITION.UPDATE",
  DELETE: "POSITION.DELETE",
};

export default {
  PERMISSION_POSITION_KEY,
  PERMISSION_ON_LEAVE_KEY,
  PERMISSION_ROLE_KEY,
  PERMISSION_SALARY_MANAGER_KEY,
  PERMISSION_SALARY_APPROVAL_KEY,
  PERMISSION_USER_KEY,
  PERMISSION_EVENT_KEY,
  PERMISSION_WORK_CALENDAR_KEY,
  PERMISSION_PROJECT_KEY,
};
